name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    name: Run the PyTest tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{secrets.POPROX_CI_DB_USER}}
          POSTGRES_PASSWORD: ${{secrets.POPROX_CI_DB_PASSWORD}}
          POSTGRES_DB: poprox
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5433:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install this package
        run: |
          pip install -e .[dev]

      - name: Apply database migrations
        working-directory: ./poprox-db
        run: |
          alembic upgrade heads
        env:
          POPROX_DB_USER: ${{secrets.POPROX_CI_DB_USER}}
          POPROX_DB_PASSWORD: ${{secrets.POPROX_CI_DB_PASSWORD}}
          POPROX_DB_PORT: 5433

      - name: Run tests
        run: |
          python -m pytest -v tests/
        env:
          POPROX_DB_USER: ${{secrets.POPROX_CI_DB_USER}}
          POPROX_DB_PASSWORD: ${{secrets.POPROX_CI_DB_PASSWORD}}
          POPROX_DB_PORT: 5433
