name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    name: Run the PyTest tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: poprox_ci
          POSTGRES_PASSWORD: poprox_ci_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5433:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Apply database migrations
        run: |
          alembic upgrade heads

      - name: Install this package
        run: |
          pip install -e .[dev]

      - name: Run tests
        run: |
          python -m pytest -v tests/
